import '../services/locale_service.dart';
import 'memory.dart';

/// Ежедневное «задание для пары» — лёгкий тёплый импульс поделиться моментом,
/// привязанный к типу воспоминания ([MemoryType]). Выполнение = создание пина
/// этого типа в Ленте воспоминаний. Награда — 1 монета (начисляется серверным
/// роутом, см. pb_hooks/coins.pb.js), поэтому задания намеренно простые: одно
/// действие «за минуту», всегда «поделись», а не «сделай задание».
///
/// Каталог статичен и типобезопасен (по образцу [ProfileIcon.all]); набор на
/// день выбирается детерминированно по (дата + pairId), поэтому у обоих
/// партнёров задания совпадают без обращения к серверу.
class DailyTask {
  /// Стабильный id — по нему хранится прогресс и идёт детерминированный выбор.
  final String id;

  /// Какой пин закрывает задание.
  final MemoryType type;

  final String _ru;
  final String _en;

  const DailyTask(this.id, this.type, this._ru, this._en);

  /// Текст задания на текущем языке. Токен `{p}` заменяется именем партнёра
  /// (или локализованным «партнёр», если имя пусто).
  String title(String partnerName) {
    final p = partnerName.trim().isNotEmpty
        ? partnerName.trim()
        : LocaleService.current.partnerFallback;
    final raw = LocaleService.instance.isRussian ? _ru : _en;
    return raw.replaceAll('{p}', p);
  }

  /// Эмодзи типа пина (переиспользуем [Memory.typeEmoji] через фиктивный доступ
  /// к таблице эмодзи — сам маппинг живёт в модели памяти).
  String get emoji {
    switch (type) {
      case MemoryType.photo:
        return '📷';
      case MemoryType.video:
        return '🎬';
      case MemoryType.location:
        return '📍';
      case MemoryType.music:
        return '🎵';
      case MemoryType.text:
        return '📝';
      case MemoryType.videoLink:
        return '🎬';
      case MemoryType.book:
        return '📚';
      case MemoryType.movie:
        return '🎬';
    }
  }

  static DailyTask? byId(String id) {
    for (final t in all) {
      if (t.id == id) return t;
    }
    return null;
  }

  /// Полный каталог. Упор на самые лёгкие типы (фото/заметка) — чтобы задание
  /// хотелось выполнить, а не откладывать.
  static const List<DailyTask> all = <DailyTask>[
    // ── 📷 Фото — сняла и готово ──────────────────────────────────────────
    DailyTask('photo_now', MemoryType.photo,
        'Сфоткай, что видишь прямо сейчас', 'Snap what you see right now'),
    DailyTask('photo_smile', MemoryType.photo,
        'Селфи с улыбкой для {p}', 'A smiling selfie for {p}'),
    DailyTask('photo_drink', MemoryType.photo,
        'Покажи, что пьёшь', "Show what you're drinking"),
    DailyTask('photo_food', MemoryType.photo,
        'Сфоткай свою еду', 'Snap your food'),
    DailyTask('photo_window', MemoryType.photo,
        'Твой вид из окна сегодня', 'Your view from the window today'),
    DailyTask('photo_sky', MemoryType.photo,
        'Сфоткай небо над тобой', 'Snap the sky above you'),
    DailyTask('photo_outfit', MemoryType.photo,
        'Покажи свой сегодняшний образ', "Show today's outfit"),
    DailyTask('photo_shoes', MemoryType.photo,
        'Сфоткай свою обувь сегодня', 'Snap your shoes today'),
    DailyTask('photo_here', MemoryType.photo,
        'Покажи, где ты сейчас', 'Show where you are right now'),
    DailyTask('photo_pet', MemoryType.photo,
        'Сфоткай питомца (или чужого котика)', 'Snap a pet (or a stray cat)'),
    DailyTask('photo_hand', MemoryType.photo,
        'Сфоткай свою руку — {p} захочет её сжать',
        "Snap your hand — {p} will want to hold it"),
    DailyTask('photo_left', MemoryType.photo,
        'Сфоткай, что слева от тебя', "Snap what's to your left"),
    DailyTask('photo_morning', MemoryType.photo,
        'Первое, что увидел утром', 'The first thing you saw this morning'),
    DailyTask('photo_beautiful', MemoryType.photo,
        'Сфоткай что-то красивое рядом', 'Snap something beautiful nearby'),
    DailyTask('photo_snack', MemoryType.photo,
        'Покажи свой перекус', 'Show your snack'),
    DailyTask('photo_mirror', MemoryType.photo,
        'Зеркальное селфи', 'A mirror selfie'),
    DailyTask('photo_cozy', MemoryType.photo,
        'Сфоткай самое уютное место рядом', 'Snap the cosiest spot near you'),
    DailyTask('photo_reminds', MemoryType.photo,
        'Сфоткай то, что напомнило о {p}',
        'Snap something that reminded you of {p}'),
    DailyTask('photo_best', MemoryType.photo,
        'Лучший момент дня — в кадр', 'Capture the best moment of your day'),
    DailyTask('photo_hobby', MemoryType.photo,
        'Покажи, чем занят прямо сейчас', "Show what you're up to right now"),
    DailyTask('photo_wink', MemoryType.photo,
        'Подмигни в камеру для {p}', 'Wink at the camera for {p}'),
    DailyTask('photo_color', MemoryType.photo,
        'Найди что-то любимого цвета {p} и сфоткай',
        "Find something in {p}'s favourite colour and snap it"),

    // ── 📝 Заметка — пара тёплых слов ─────────────────────────────────────
    DailyTask('text_grateful', MemoryType.text,
        'За что ты сегодня благодарен {p}?',
        'What are you grateful to {p} for today?'),
    DailyTask('text_three', MemoryType.text,
        'Опиши {p} тремя словами', 'Describe {p} in three words'),
    DailyTask('text_compliment', MemoryType.text,
        'Отправь {p} комплимент', 'Send {p} a compliment'),
    DailyTask('text_miss', MemoryType.text,
        'Напиши, чего тебе не хватает рядом с {p}',
        'Write what you miss about {p} right now'),
    DailyTask('text_love', MemoryType.text,
        'За что ты любишь {p}? Одно предложение',
        'Why do you love {p}? One sentence'),
    DailyTask('text_memory', MemoryType.text,
        'Вспомни любимый момент с {p}',
        'Recall your favourite moment with {p}'),
    DailyTask('text_smile', MemoryType.text,
        'Что заставило тебя улыбнуться сегодня?',
        'What made you smile today?'),
    DailyTask('text_dream', MemoryType.text,
        'О чём ты мечтаешь для вас двоих?',
        'What do you dream of for the two of you?'),
    DailyTask('text_firstthing', MemoryType.text,
        'Что первым делом скажешь {p} при встрече?',
        "First thing you'll say to {p} when you meet?"),
    DailyTask('text_nickname', MemoryType.text,
        'Придумай {p} новое милое прозвище',
        'Make up a cute new nickname for {p}'),
    DailyTask('text_ifhere', MemoryType.text,
        'Что бы вы делали, будь {p} сейчас рядом?',
        'What would you do if {p} were here now?'),
    DailyTask('text_proud', MemoryType.text,
        'Чем ты гордишься в {p}?', 'What are you proud of {p} for?'),
    DailyTask('text_good', MemoryType.text,
        'Расскажи о хорошем, что случилось сегодня',
        'Share something good that happened today'),
    DailyTask('text_wish', MemoryType.text,
        'Пожелай {p} хорошего вечера своими словами',
        'Wish {p} a good evening in your own words'),
    DailyTask('text_thanks', MemoryType.text,
        'Скажи {p} спасибо за что-то мелкое',
        'Thank {p} for something small'),
    DailyTask('text_hug', MemoryType.text,
        'Опиши, как обнимешь {p} при встрече',
        "Describe how you'll hug {p} when you meet"),

    // ── 📍 Локация — одно нажатие ─────────────────────────────────────────
    DailyTask('loc_here', MemoryType.location,
        'Отметь, где ты сейчас', 'Check in where you are now'),
    DailyTask('loc_favorite', MemoryType.location,
        'Отметь место, где вам было хорошо вдвоём',
        'Mark a place you loved together'),
    DailyTask('loc_coffee', MemoryType.location,
        'Отметь, где пьёшь кофе', "Mark where you're having coffee"),
    DailyTask('loc_dream', MemoryType.location,
        'Отметь место, куда хочешь поехать с {p}',
        'Mark a place you want to go with {p}'),
    DailyTask('loc_walk', MemoryType.location,
        'Гуляешь? Отметь, где ты', 'Out for a walk? Mark the spot'),
    DailyTask('loc_home', MemoryType.location,
        'Отметь свой любимый уголок дома',
        'Mark your favourite corner at home'),
    DailyTask('loc_food', MemoryType.location,
        'Отметь, где вкусно поел', 'Mark where you ate something tasty'),
    DailyTask('loc_first', MemoryType.location,
        'Отметь место вашего первого свидания',
        'Mark the place of your first date'),
    DailyTask('loc_view', MemoryType.location,
        'Отметь точку с лучшим видом рядом', 'Mark the best view nearby'),

    // ── 🎵 Музыка — поделись треком ───────────────────────────────────────
    DailyTask('mus_now', MemoryType.music,
        'Что играет у тебя прямо сейчас?', "What's playing for you right now?"),
    DailyTask('mus_reminds', MemoryType.music,
        'Песня, под которую вспоминаешь {p}',
        'A song that reminds you of {p}'),
    DailyTask('mus_dedicate', MemoryType.music,
        'Посвяти {p} песню', 'Dedicate a song to {p}'),
    DailyTask('mus_dance', MemoryType.music,
        'Под что бы вы потанцевали вдвоём?', 'What would you two dance to?'),
    DailyTask('mus_mood', MemoryType.music,
        'Песня под твоё настроение сейчас', 'A song for your mood right now'),
    DailyTask('mus_oursong', MemoryType.music,
        'Ваша песня — поделись', 'Your song — share it'),
    DailyTask('mus_discover', MemoryType.music,
        'Трек, который недавно зацепил', 'A track that recently caught you'),
    DailyTask('mus_morning', MemoryType.music,
        'Что бы поставил вам на утро?', 'What would you play for your morning?'),
    DailyTask('mus_road', MemoryType.music,
        'Песня для дороги к {p}', 'A song for the road to {p}'),

    // ── 🎬 Фильм ──────────────────────────────────────────────────────────
    DailyTask('mov_watch', MemoryType.movie,
        'Что хотите посмотреть вместе?', 'What do you want to watch together?'),
    DailyTask('mov_fav', MemoryType.movie,
        'Твой любимый фильм — покажи {p}', 'Your favourite film — show {p}'),
    DailyTask('mov_comedy', MemoryType.movie,
        'Комедия на вечер вдвоём', 'A comedy for an evening together'),
    DailyTask('mov_series', MemoryType.movie,
        'Сериал, который стоит начать вместе',
        'A series worth starting together'),
    DailyTask('mov_childhood', MemoryType.movie,
        'Фильм из детства, который любишь', 'A childhood film you love'),
    DailyTask('mov_cry', MemoryType.movie,
        'Фильм, над которым не стыдно поплакать', 'A film worth crying over'),

    // ── 📚 Книга ──────────────────────────────────────────────────────────
    DailyTask('book_recommend', MemoryType.book,
        'Книга, которую советуешь {p}', "A book you'd recommend to {p}"),
    DailyTask('book_reading', MemoryType.book,
        'Что читаешь сейчас?', 'What are you reading now?'),
    DailyTask('book_changed', MemoryType.book,
        'Книга, которая тебя изменила', 'A book that changed you'),
    DailyTask('book_together', MemoryType.book,
        'Книга, которую хочешь прочитать вместе',
        'A book to read together'),
    DailyTask('book_quote', MemoryType.book,
        'Любимая цитата из книги', 'A favourite book quote'),

    // ── 🎬 Видео-ссылка ───────────────────────────────────────────────────
    DailyTask('vid_laugh', MemoryType.videoLink,
        'Видео, которое тебя рассмешило', 'A video that made you laugh'),
    DailyTask('vid_show', MemoryType.videoLink,
        'Ролик, который хочешь показать {p}', 'A clip you want to show {p}'),
    DailyTask('vid_wow', MemoryType.videoLink,
        'Видео, которое удивило', 'A video that amazed you'),
    DailyTask('vid_cute', MemoryType.videoLink,
        'Милейшее видео дня', 'The cutest video of the day'),

    // ═════════ ЧАСТЬ 2 — добор до 200 ═════════

    // ── 📷 Фото ───────────────────────────────────────────────────────────
    DailyTask('photo_right', MemoryType.photo,
        'Сфоткай, что справа от тебя', "Snap what's to your right"),
    DailyTask('photo_feet', MemoryType.photo,
        'Сфоткай вид «сверху вниз» — на свои ноги',
        'Snap the view down at your feet'),
    DailyTask('photo_madeday', MemoryType.photo,
        'Сфоткай то, что сегодня тебя порадовало',
        'Snap something that made your day'),
    DailyTask('photo_coffee', MemoryType.photo,
        'Сфоткай свою кружку', 'Snap your mug'),
    DailyTask('photo_sweet', MemoryType.photo,
        'Покажи что-нибудь сладкое рядом', 'Show something sweet nearby'),
    DailyTask('photo_desk', MemoryType.photo,
        'Покажи свой рабочий беспорядок', 'Show your desk mess'),
    DailyTask('photo_infront', MemoryType.photo,
        'Что перед тобой прямо сейчас?', "What's in front of you right now?"),
    DailyTask('photo_hands_busy', MemoryType.photo,
        'Сфоткай, чем заняты твои руки',
        'Snap what your hands are busy with'),
    DailyTask('photo_light', MemoryType.photo,
        'Сфоткай красивый свет рядом', 'Snap some pretty light nearby'),
    DailyTask('photo_plant', MemoryType.photo,
        'Сфоткай растение поблизости', 'Snap a plant nearby'),
    DailyTask('photo_street', MemoryType.photo,
        'Сфоткай свою улицу', 'Snap your street'),
    DailyTask('photo_sunset', MemoryType.photo,
        'Закат или рассвет — успей поймать', 'Catch the sunset or sunrise'),
    DailyTask('photo_watching', MemoryType.photo,
        'Сфоткай, что читаешь или смотришь',
        "Snap what you're reading or watching"),
    DailyTask('photo_smalljoy', MemoryType.photo,
        'Маленькая радость дня — в кадр', 'A small joy of the day — snap it'),
    DailyTask('photo_reflection', MemoryType.photo,
        'Найди отражение и сфоткай', 'Find a reflection and snap it'),
    DailyTask('photo_texture', MemoryType.photo,
        'Сфоткай приятную текстуру рядом', 'Snap a nice texture nearby'),
    DailyTask('photo_favthing', MemoryType.photo,
        'Сфоткай любимую вещь под рукой', 'Snap a favourite thing at hand'),
    DailyTask('photo_gift', MemoryType.photo,
        'Что бы ты подарил {p}? Сфоткай', 'What would you gift {p}? Snap it'),
    DailyTask('photo_weather', MemoryType.photo,
        'Покажи погоду за окном', 'Show the weather outside'),
    DailyTask('photo_cook', MemoryType.photo,
        'Готовишь? Покажи процесс', 'Cooking? Show the process'),
    DailyTask('photo_hair', MemoryType.photo,
        'Покажи свою причёску сегодня', 'Show your hairstyle today'),
    DailyTask('photo_afterwalk', MemoryType.photo,
        'После прогулки или тренировки — селфи',
        'A selfie after a walk or workout'),
    DailyTask('photo_night', MemoryType.photo,
        'Сфоткай вечерний вид', 'Snap the evening view'),
    DailyTask('photo_name', MemoryType.photo,
        'Напиши имя {p} и сфоткай', "Write {p}'s name and snap it"),
    DailyTask('photo_round', MemoryType.photo,
        'Найди что-то круглое и сфоткай', 'Find something round and snap it'),
    DailyTask('photo_shadow', MemoryType.photo,
        'Сфоткай свою тень', 'Snap your shadow'),
    DailyTask('photo_soft', MemoryType.photo,
        'Сфоткай что-то мягкое рядом', 'Snap something soft nearby'),
    DailyTask('photo_favspot', MemoryType.photo,
        'Твоё любимое место дома — в кадр',
        'Your favourite spot at home — snap it'),
    DailyTask('photo_new', MemoryType.photo,
        'Сфоткай что-то новое у тебя', "Snap something new you've got"),
    DailyTask('photo_flower', MemoryType.photo,
        'Найди цветок и сфоткай для {p}',
        'Find a flower and snap it for {p}'),
    DailyTask('photo_sunray', MemoryType.photo,
        'Поймай солнечный лучик', 'Catch a ray of sun'),
    DailyTask('photo_detail', MemoryType.photo,
        'Сфоткай красивую деталь вокруг',
        'Snap a beautiful detail around you'),
    DailyTask('photo_evening', MemoryType.photo,
        'Как выглядит твой вечер?', 'What does your evening look like?'),
    DailyTask('photo_corner', MemoryType.photo,
        'Сфоткай самый милый угол дома',
        'Snap the cutest corner of your home'),
    DailyTask('photo_blue', MemoryType.photo,
        'Найди рядом что-то синее и сфоткай',
        'Find something blue nearby and snap it'),
    DailyTask('photo_smile2', MemoryType.photo,
        'Улыбнись как {p} и сфоткай', 'Smile like {p} and snap it'),
    DailyTask('photo_drinkfav', MemoryType.photo,
        'Твой любимый напиток в кадре', 'Your favourite drink in frame'),
    DailyTask('photo_today', MemoryType.photo,
        'Один кадр, который описывает твой день',
        'One shot that sums up your day'),

    // ── 📝 Заметка ────────────────────────────────────────────────────────
    DailyTask('text_bestthing', MemoryType.text,
        'Что лучшее в {p}?', "What's the best thing about {p}?"),
    DailyTask('text_laugh', MemoryType.text,
        'Когда {p} рассмешил тебя в последний раз?',
        'When did {p} last make you laugh?'),
    DailyTask('text_lyric', MemoryType.text,
        'Строчка из песни, которая про вас',
        "A song lyric that's about you two"),
    DailyTask('text_perfectdate', MemoryType.text,
        'Опиши ваше идеальное свидание', 'Describe your perfect date'),
    DailyTask('text_goodmorning', MemoryType.text,
        'Доброе утро для {p} своими словами',
        'A good-morning to {p} in your own words'),
    DailyTask('text_goodnight', MemoryType.text,
        'Спокойной ночи для {p}', 'A goodnight for {p}'),
    DailyTask('text_admire', MemoryType.text,
        'Чем ты восхищаешься в {p}?', 'What do you admire about {p}?'),
    DailyTask('text_taught', MemoryType.text,
        'Чему тебя научил {p}?', 'What has {p} taught you?'),
    DailyTask('text_smell', MemoryType.text,
        'Какой запах напоминает о {p}?', 'What smell reminds you of {p}?'),
    DailyTask('text_escape', MemoryType.text,
        'Куда бы вы сбежали вдвоём?', 'Where would you escape together?'),
    DailyTask('text_firstimpression', MemoryType.text,
        'Первое впечатление о {p}?', 'Your first impression of {p}?'),
    DailyTask('text_habit', MemoryType.text,
        'Какая привычка {p} тебя умиляет?',
        "Which of {p}'s habits melts you?"),
    DailyTask('text_safe', MemoryType.text,
        'Когда рядом с {p} тебе спокойнее всего?',
        'When do you feel safest with {p}?'),
    DailyTask('text_support', MemoryType.text,
        'За что хочешь поддержать {p}?', 'What would you cheer {p} on for?'),
    DailyTask('text_word', MemoryType.text,
        'Одно слово про твой день', 'One word for your day'),
    DailyTask('text_weekbest', MemoryType.text,
        'Лучший момент недели', 'The best moment of your week'),
    DailyTask('text_promise', MemoryType.text,
        'Маленькое обещание для {p}', 'A little promise for {p}'),
    DailyTask('text_weekend', MemoryType.text,
        'Идеальные выходные с {p}', 'An ideal weekend with {p}'),
    DailyTask('text_cookfor', MemoryType.text,
        'Что бы приготовил для {p}?', 'What would you cook for {p}?'),
    DailyTask('text_sweet', MemoryType.text,
        'Просто напиши что-то милое', 'Just write something sweet'),
    DailyTask('text_smallthing', MemoryType.text,
        'За какую мелочь ты благодарен сегодня?',
        'What small thing are you grateful for today?'),
    DailyTask('text_rightnow', MemoryType.text,
        'Что бы ты сделал для {p} прямо сейчас?',
        'What would you do for {p} right now?'),
    DailyTask('text_energize', MemoryType.text,
        'Что заряжает тебя рядом с {p}?', 'What energises you about {p}?'),
    DailyTask('text_firstdate', MemoryType.text,
        'Вспомни ваше первое свидание', 'Recall your first date'),
    DailyTask('text_callreason', MemoryType.text,
        'Найди повод позвонить {p}', 'Find a reason to call {p}'),
    DailyTask('text_whysmile', MemoryType.text,
        'Пусть {p} узнает, почему ты улыбаешься',
        "Let {p} know why you're smiling"),
    DailyTask('text_win', MemoryType.text,
        'Твоя маленькая победа сегодня', 'Your small win today'),
    DailyTask('text_feellike', MemoryType.text,
        'Чего тебе сейчас хочется?', 'What do you feel like right now?'),
    DailyTask('text_trait', MemoryType.text,
        'Любимая черта {p}?', 'Your favourite trait of {p}?'),
    DailyTask('text_justbeing', MemoryType.text,
        'Скажи спасибо {p} просто за то, что он есть',
        'Thank {p} just for being here'),
    DailyTask('text_triptogether', MemoryType.text,
        'Куда мечтаешь поехать вместе?',
        'Where do you dream of travelling together?'),
    DailyTask('text_noteyear', MemoryType.text,
        'Оставь послание вам через год',
        'Leave a note to you two a year from now'),
    DailyTask('text_favmemory2', MemoryType.text,
        'Момент с {p}, который хочется повторить',
        'A moment with {p} you want to relive'),
    DailyTask('text_grateful2', MemoryType.text,
        'Три вещи, за которые ты благодарен сегодня',
        'Three things you are grateful for today'),

    // ── 📍 Локация ────────────────────────────────────────────────────────
    DailyTask('loc_work', MemoryType.location,
        'Отметь, где ты работаешь или учишься',
        'Mark where you work or study'),
    DailyTask('loc_lunch', MemoryType.location,
        'Отметь, где обедал', 'Mark where you had lunch'),
    DailyTask('loc_park', MemoryType.location,
        'Отметь ближайший парк', 'Mark the nearest park'),
    DailyTask('loc_shop', MemoryType.location,
        'Отметь, где сейчас за покупками', "Mark where you're shopping"),
    DailyTask('loc_gym', MemoryType.location,
        'Отметь, где тренировался', 'Mark where you worked out'),
    DailyTask('loc_sunset', MemoryType.location,
        'Отметь точку с красивым закатом',
        'Mark a spot with a nice sunset'),
    DailyTask('loc_shared', MemoryType.location,
        'Отметь место с общим воспоминанием',
        'Mark a place with a shared memory'),
    DailyTask('loc_newplace', MemoryType.location,
        'Отметь новое место, где сегодня был',
        'Mark a new place you visited today'),
    DailyTask('loc_kiss', MemoryType.location,
        'Отметь место вашего первого поцелуя',
        'Mark the place of your first kiss'),
    DailyTask('loc_cafe', MemoryType.location,
        'Отметь ваше любимое кафе', 'Mark your favourite café'),
    DailyTask('loc_water', MemoryType.location,
        'Отметь место у воды рядом', 'Mark a spot by the water nearby'),
    DailyTask('loc_town', MemoryType.location,
        'Отметь любимое место в твоём городе',
        'Mark a favourite place in your town'),
    DailyTask('loc_night', MemoryType.location,
        'Отметь, где ты этим вечером', 'Mark where you are this evening'),
    DailyTask('loc_dreamcountry', MemoryType.location,
        'Отметь страну мечты для вас двоих',
        'Mark a dream country for you two'),
    DailyTask('loc_calm', MemoryType.location,
        'Отметь место, где тебе спокойно',
        'Mark a place where you feel calm'),
    DailyTask('loc_next', MemoryType.location,
        'Куда пойдёте в следующий раз вместе?',
        'Where will you go together next?'),
    DailyTask('loc_hidden', MemoryType.location,
        'Отметь уютное местечко, о котором мало кто знает',
        'Mark a cosy hidden spot'),
    DailyTask('loc_skyview', MemoryType.location,
        'Отметь место с видом на небо',
        'Mark a spot with a view of the sky'),
    DailyTask('loc_market', MemoryType.location,
        'Отметь рынок или магазинчик рядом',
        'Mark a market or little shop nearby'),

    // ── 🎵 Музыка ─────────────────────────────────────────────────────────
    DailyTask('mus_energy2', MemoryType.music,
        'Твой трек для энергии', 'Your track for energy'),
    DailyTask('mus_sad', MemoryType.music,
        'Песня для грустного настроения', 'A song for a blue mood'),
    DailyTask('mus_happy', MemoryType.music,
        'Песня, которая тебя радует', 'A song that makes you happy'),
    DailyTask('mus_firstdate', MemoryType.music,
        'Песня, что играла на вашем первом свидании?',
        'A song from your first date?'),
    DailyTask('mus_karaoke', MemoryType.music,
        'Что бы вы спели в караоке вдвоём?',
        'What would you two sing at karaoke?'),
    DailyTask('mus_childhood', MemoryType.music,
        'Песня из детства', 'A song from your childhood'),
    DailyTask('mus_guilty', MemoryType.music,
        'Твой «стыдный» любимый трек', 'Your guilty-pleasure track'),
    DailyTask('mus_relax', MemoryType.music,
        'Что слушаешь, чтобы расслабиться?',
        'What do you listen to to relax?'),
    DailyTask('mus_playlist', MemoryType.music,
        'Плейлист-настроение для {p}', 'A mood playlist for {p}'),
    DailyTask('mus_newfav', MemoryType.music,
        'Новый любимый трек', 'A new favourite track'),
    DailyTask('mus_slow', MemoryType.music,
        'Медленная песня для вас двоих',
        'A slow song for the two of you'),
    DailyTask('mus_wakeup', MemoryType.music,
        'Что бы поставил, чтобы разбудить {p}?',
        'What would you play to wake {p} up?'),
    DailyTask('mus_summer', MemoryType.music,
        'Песня, что звучит как лето', 'A song that sounds like summer'),
    DailyTask('mus_cover', MemoryType.music,
        'Любимый кавер', 'A favourite cover'),
    DailyTask('mus_instrumental', MemoryType.music,
        'Мелодия без слов, которая цепляет',
        'A wordless tune that grabs you'),
    DailyTask('mus_latenight', MemoryType.music,
        'Песня для позднего вечера', 'A song for late night'),
    DailyTask('mus_dance2', MemoryType.music,
        'Трек, под который хочется танцевать',
        'A track that makes you want to dance'),
    DailyTask('mus_nostalgia', MemoryType.music,
        'Песня, что возвращает в прошлое',
        'A song that takes you back'),
    DailyTask('mus_week', MemoryType.music,
        'Твой трек этой недели', 'Your track of the week'),

    // ── 🎬 Фильм ──────────────────────────────────────────────────────────
    DailyTask('mov_rewatch', MemoryType.movie,
        'Фильм, который пересматриваешь всегда',
        'A film you always rewatch'),
    DailyTask('mov_scary', MemoryType.movie,
        'Ужастик, чтобы прижаться друг к другу',
        'A scary film to cuddle through'),
    DailyTask('mov_animation', MemoryType.movie,
        'Мультик на двоих', 'An animated film for two'),
    DailyTask('mov_datenight', MemoryType.movie,
        'Идеальный фильм для свидания', 'The perfect date-night film'),
    DailyTask('mov_recommend', MemoryType.movie,
        'Фильм, который советуешь {p}', "A film you'd recommend to {p}"),
    DailyTask('mov_underrated', MemoryType.movie,
        'Недооценённый фильм, который любишь',
        'An underrated film you love'),
    DailyTask('mov_binge', MemoryType.movie,
        'Сериал, который проглотил залпом', 'A series you binged'),
    DailyTask('mov_feelgood', MemoryType.movie,
        'Фильм, поднимающий настроение', 'A feel-good film'),

    // ── 📚 Книга ──────────────────────────────────────────────────────────
    DailyTask('book_bedtime', MemoryType.book,
        'Книга, которую читаешь перед сном',
        'A book you read before bed'),
    DailyTask('book_author', MemoryType.book,
        'Любимый автор — поделись', 'Your favourite author — share'),
    DailyTask('book_childhood', MemoryType.book,
        'Книга из детства', 'A book from your childhood'),
    DailyTask('book_wishlist', MemoryType.book,
        'Книга, которую давно хочешь прочитать',
        "A book you've long wanted to read"),
    DailyTask('book_gift', MemoryType.book,
        'Книга, которую подарил бы {p}', "A book you'd gift {p}"),
    DailyTask('book_reread', MemoryType.book,
        'Книга, которую перечитывал', "A book you've reread"),
    DailyTask('book_comfort', MemoryType.book,
        'Книга, к которой возвращаешься за уютом',
        'A comfort book you return to'),

    // ── 🎬 Видео-ссылка ───────────────────────────────────────────────────
    DailyTask('vid_music', MemoryType.videoLink,
        'Клип любимой песни', 'A music video of a favourite song'),
    DailyTask('vid_inspire', MemoryType.videoLink,
        'Видео, которое вдохновляет', 'A video that inspires you'),
    DailyTask('vid_learn', MemoryType.videoLink,
        'Видео, из которого узнал что-то новое',
        'A video you learned something from'),
    DailyTask('vid_watchtogether', MemoryType.videoLink,
        'Видео, которое хочешь посмотреть с {p}',
        'A video to watch with {p}'),
  ];
}
